# Node CircleCI 2.0 configuration file to DTA cloud 2.0

version: 2
jobs:

  # DEPLOY-STAGING JOB
  # installing dependencies, testing, building assets and deploying to staging
  deploy-staging:
    docker:
      - image: circleci/node:latest

    steps:
      - run: rm -rf node_modules       # delete node_modules to bust caching
      - checkout                       # get the files from the repo (why would you ever not want the files????)
      - run: npm install               # duh
      - run: npm test                  # testing first!
      - run: npm run build             # required build step
      - run: rm -rf node_modules       # delete node_modules folder again to not push it to cf
      - run: sudo apt-get install apt-transport-https
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf-cli
      - run: cf install-plugin https://github.com/govau/autopilot/releases/download/0.0.5-venapp/autopilot-linux -f
      - run: cf version                # log what version we are running
      - run: cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_STAGING
      - run: cf zero-downtime-push furnace -f manifest-staging.yml


  # DEPLOY-PROD JOB
  # installing dependencies, testing, building assets and deploying to production
  deploy-prod:
    docker:
      - image: circleci/node:latest

    steps:
      - run: rm -rf node_modules
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: rm -rf node_modules
      - run: sudo apt-get install apt-transport-https
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf-cli
      - run: cf install-plugin https://github.com/govau/autopilot/releases/download/0.0.5-venapp/autopilot-linux -f
      - run: cf version
      - run: cf login -a $CF_API_PROD -o $CF_ORG -s $CF_SPACE -u $CF_USERNAME -p $CF_PASSWORD_PROD
      - run: cf zero-downtime-push furnace -f manifest-prod.yml


# OUR WORKFLOW
# this is where we orchestrate our jobs
workflows:
  version: 2
  testing-deploying:
    jobs:

      - deploy-staging:     # run deploy staging
          filters:
            branches:
              only: develop # and only in the `develop` branch

      - deploy-prod:        # run deploy production
          filters:
            branches:
              only: master  # and only in the `master` branch
